### ISSUE TITLE
praisonai chat returns exit code 0 when OpenAI API key is invalid

### ISSUE THREAD

**Issue by Dhivya-Bharathy** [MervinPraison/PraisonAI#2562]
### Problem statement

When **`OPENAI_API_KEY`** is invalid, **`praisonai chat`** logs HTTP 401 warnings to stderr but exits with **code 0**. Shell scripts, CI pipelines, and automation cannot detect authentication failure without parsing log output.

Hermes baseline on the identical test: concise `HTTP 401` message and **exit 1**.

### Business impact

| Stakeholder | Impact |
|-------------|--------|
| CI/CD | Pipelines report success despite auth misconfiguration |
| Script authors | Must grep stderr instead of checking `$LASTEXITCODE` |
| Onboarding | Wrong API key looks like “empty success” in `--output plain` mode |

### Technical impact

- **Error classification works** — `error_classifier.py` correctly tags 401 as `AUTH` / `should_rotate_credential=True`
- **Exit propagation missing** — Typer `chat_main()` never maps auth failure to `typer.Exit(1)`
- **Silent plain mode** — single-prompt path prints nothing when response is `None`

### User impact

User sets wrong key → runs `praisonai chat --output plain -- "Hello"` → sees warnings in stderr (easy to miss) → **exit 0** → downstream automation assumes success.

---

## Environment

| Field | Value |
|-------|-------|
| **Repository** | [MervinPraison/PraisonAI](https://github.com/MervinPraison/PraisonAI) |
| **Version tested** | 4.6.102, **4.6.107** |
| **Dependency** | praisonaiagents 1.6.107 |
| **OS** | Windows 10 |
| **Python** | 3.13.2 |
| **Model** | gpt-4o-mini |
| **Validation date** | 2026-07-02 |

---

### Unexpected (actual)

```powershell
$env:OPENAI_API_KEY = "sk-invalid-key-for-test"
praisonai chat --output plain --model gpt-4o-mini -- "Hello"
```

**stderr (excerpt):**
```
openai_client.py:1465 WARNING Responses API failed, falling back to Chat Completions:
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-inval***********test',
'type': 'invalid_request_error', 'code': 'invalid_api_key', 'param': None}, 'status': 401}
openai_client.py:1486 ERROR Error creating async completion: Error code: 401 - ...
chat_mixin.py:1485 WARNING [Praison] Authentication failed for openai.
Check API credentials. (credential rotation not yet implemented)
```

**stdout:** *(empty)*  
**exit code:** `0` ❌

### Expected

| Condition | stdout | stderr | Exit code |
|-----------|--------|--------|-----------|
| Valid key, success | Model answer | minimal | **0** |
| Invalid API key | empty or one-line error | optional detail | **1** |
| Missing API key | concise message | optional | **1** |
| Rate limit 429 | error message | logged | **non-zero** |

### Competitive comparison (same test)

| Product | Command | User-visible error | Exit code |
|---------|---------|-------------------|-----------|
| **Hermes** | `hermes chat -q "Hello" -Q -m gpt-4o-mini` | `HTTP 401: Incorrect API key provided...` | **1** |
| **PraisonAI** | `praisonai chat --output plain -- "Hello"` | 401 in stderr logs only | **0** ❌ |

---

## Reproduction

```powershell
# Save real key, inject invalid key
$saved = $env:OPENAI_API_KEY
$env:OPENAI_API_KEY = "sk-invalid-key-for-test"

praisonai chat --output plain --model gpt-4o-mini -- "Hello"
Write-Host "Exit code: $LASTEXITCODE"   # prints 0 — should be non-zero

$env:OPENAI_API_KEY = $saved
```

Minimal script check:
```powershell
praisonai chat --output plain --model gpt-4o-mini -- "Hello"
if ($LASTEXITCODE -ne 0) { "PASS" } else { "FAIL: auth error not reflected in exit code" }
```

---

### Current flow (broken exit propagation)

```mermaid
flowchart TB
  subgraph CLI["PraisonAI CLI"]
    CM["chat.py chat_main()"]
    TUI["async_tui.py AsyncTUI.run_single()"]
    EP["_execute_prompt()"]
  end
  subgraph Agents["praisonaiagents"]
    AG["Agent.start() / astart()"]
    CMIX["chat_mixin.py _handle_async_llm_error()"]
    EC["llm/error_classifier.py classify AUTH"]
    OC["openai_client.py 401 Responses → Chat fallback"]
  end
  CM -->|"prompt set"| TUI
  TUI --> EP
  EP --> AG
  AG --> OC
  OC -->|401| CMIX
  CMIX --> EC
  EC -->|should_rotate_credential=True| LOG["logging.warning auth failed"]
  LOG --> RET["return None / empty"]
  RET --> CM
  CM -->|"if response: print"| OUT["stdout empty"]
  CM --> EXIT["implicit exit 0 ❌"]
```

### Sequence diagram

```mermaid
sequenceDiagram
  participant U as User
  participant C as chat_main
  participant T as AsyncTUI
  participant A as Agent
  participant O as OpenAI client
  participant E as error_classifier

  U->>C: chat --output plain "Hello"
  C->>T: run_single(prompt)
  T->>A: astart(prompt)
  A->>O: chat completion
  O-->>A: HTTP 401 invalid_api_key
  A->>E: classify → AUTH
  E-->>A: should_rotate_credential=True
  A->>A: log WARNING (chat_mixin ~1485)
  A-->>T: None / empty response
  T-->>C: None
  Note over C: if response: print(response)<br/>else: no print
  C-->>U: exit 0 ❌
```

### Code reference table

| Symbol | Location | Role | Status |
|--------|----------|------|--------|
| `chat_main()` | `praisonai_code/cli/commands/chat.py:49` | Typer entry | ❌ No exit on auth fail |
| Single-prompt branch | `chat.py:229–233` | `if response: print(response)` | ❌ Silent on None |
| `run_single()` | `async_tui.py:1201–1203` | Delegates to `_execute_prompt` | — |
| `_execute_prompt()` | `async_tui.py:734–787` | Returns `None` on failure | ⚠️ Swallows auth |
| `classify_llm_error()` AUTH | `llm/error_classifier.py:188–198` | Sets `should_rotate_credential=True` | ✅ |
| Auth warning log | `agent/chat_mixin.py:1483–1485` | Logs only, no raise | ❌ |
| OpenAI 401 fallback | `openai_client.py:1465+` | Responses → Chat Completions | ✅ then 401 again |
| Hermes reference | `hermes chat -q` | Maps 401 → exit 1 | ✅ baseline |

### Error classifier (working layer)

```python
# praisonaiagents/llm/error_classifier.py:188–198
if category == ErrorCategory.AUTH:
    return LLMErrorClassification(
        error_category="auth",
        is_retryable=False,
        should_rotate_credential=True,
        user_message=f"Authentication failed for {provider}. Check API credentials.",
    )
```

Classification is correct; **CLI never consumes `should_rotate_credential` for exit status**.

---

### Step 1 — Agent-level auth failure flag

In `chat_mixin.py`, when `classification.should_rotate_credential` and no successful response:

```python
self._last_auth_failure = True  # or raise AuthError
```

### Step 2 — Propagate through TUI

`_execute_prompt()` should return a result object or raise on auth failure instead of `None`:

```python
if getattr(agent, "_last_auth_failure", False):
    raise typer.Exit(1)  # or return AuthFailed sentinel
```

### Step 3 — Typer exit in `chat_main`

```python
response = tui.run_single(prompt)
if response is None and tui.had_auth_failure():
    typer.echo("Authentication failed. Check API credentials.", err=True)
    raise typer.Exit(1)
if response:
    print(response)
```

### Step 4 — Optional exit code map

| Code | Meaning |
|------|---------|
| 0 | Success |
| 1 | Auth / configuration error |
| 2 | Rate limit / transient (optional) |

Document in `praisonai chat --help`.

---

## Acceptance criteria

- [ ] Invalid `OPENAI_API_KEY` → `praisonai chat --output plain -- "Hello"` exits **non-zero**
- [ ] Valid key → still exits 0 with answer
- [ ] stderr may still log details; stdout empty or concise error is OK
- [ ] Hermes-parity: script can use `$LASTEXITCODE` / `%ERRORLEVEL%` without parsing logs
- [ ] Unit test: mock 401 → CLI entry returns exit 1
- [ ] No regression on interactive REPL mode (optional: exit 1 only in single-prompt / plain)

---

## Test plan

| # | Test | Expected |
|---|------|----------|
| 1 | Invalid key, plain one-shot | exit ≠ 0 |
| 2 | Valid key, plain one-shot | exit 0, answer printed |
| 3 | Missing key entirely | exit ≠ 0 |
| 4 | PowerShell `$LASTEXITCODE` check | reflects failure |
| 5 | Compare Hermes invalid-key test | same script semantics |
| 6 | Unit: mock OpenAI 401 in chat path | Typer Exit(1) |

---

## Related

- [#2561](https://github.com/MervinPraison/PraisonAI/issues/2561) — `praisonai run` Windows Unicode (separate; invalid-key on run may hit charmap first)
- Interactive analysis: `competitive-analysis/hermes-vs-praisonai/feature-02-chat-analysis.html`

---

## Competitive reference

| Capability | Hermes `chat -q` | PraisonAI `chat --output plain` |
|------------|------------------|----------------------------------|
| Invalid key message | Clear HTTP 401 on stdout/stderr | 401 buried in logs |
| Exit code on auth fail | 1 | 0 ❌ |
| Script automation | `$?` reliable | requires stderr grep |
| Valid key one-shot | works | works |

**Comment by Dhivya-Bharathy** [comment]
# `praisonai chat` returns exit code 0 when OpenAI API key is invalid

**GitHub:** [#2562](https://github.com/MervinPraison/PraisonAI/issues/2562) — **REOPENED** (partial fix insufficient)  
**Type:** Bug · **Labels:** `bug`, `cli`, `exit-code`  
**Merged PR (partial):** [#2564](https://github.com/MervinPraison/PraisonAI/pull/2564) — `execution_failed` + log capture  
**Found:** Feature 2 competitive validation (Hermes vs PraisonAI one-shot chat), 2026-07-02  
**Re-verified:** 2026-07-02 post-merge on main @ `7059e73f8`

---

## Summary

### Problem statement

When **`OPENAI_API_KEY`** is invalid, **`praisonai chat`** logs HTTP 401 warnings to stderr but exits with **code 0**. Shell scripts, CI pipelines, and automation cannot detect authentication failure without parsing log output.

Hermes baseline on the identical test: concise `HTTP 401` message and **exit 1**.

### Post-fix status (2026-07-02 re-verification)

| Layer | Status | Notes |
|-------|--------|-------|
| GitHub issue | CLOSED → **reopening** | Closed via PR #2564 |
| Unit tests (`test_chat_auth_exit_code.py`) | **6/6 PASS** | Mocks `agent.start()` returning `None` |
| Live `praisonai chat` + invalid key | **FAIL** | exit **0**, auth warnings on stderr |
| Live `praisonai chat` + valid key | **PASS** | exit 0, answer printed (`CHAT_OK`) |
| Auth log capture | **Works** | `_LogCapture` records 401 + auth warning |
| `execution_failed` flag | **Not set** | Guard condition never triggers |

**Conclusion:** PR #2564 added `_LogCapture`, `_detect_auth_error()`, and `execution_failed` wiring, but the guard **`if auth_error and not response:` fails in production** because `agent.astart()` returns a **truthy `AutonomyResult(output='')`** object — not `None`. Unit tests pass because they mock `start()` returning `None`, not `AutonomyResult`.

### Business impact

| Stakeholder | Impact |
|-------------|--------|
| CI/CD | Pipelines report success despite auth misconfiguration |
| Script authors | Must grep stderr instead of checking `$LASTEXITCODE` |
| Onboarding | Wrong API key looks like “empty success” in `--output plain` mode |

### User impact

User sets wrong key → runs `praisonai chat --output plain -- "Hello"` → sees warnings in stderr (easy to miss) → **exit 0** → downstream automation assumes success.

---

## Environment

| Field | Value |
|-------|-------|
| **Repository** | [MervinPraison/PraisonAI](https://github.com/MervinPraison/PraisonAI) |
| **Commit tested** | `7059e73f8` (merge PR #2564) |
| **Version tested** | PraisonAI **4.6.107**, praisonai-code **0.0.5**, praisonaiagents **1.6.107** |
| **OS** | Windows 10 |
| **Python** | 3.13.2 |
| **Model** | gpt-4o-mini |
| **Validation date** | 2026-07-02 |

---

## What PR #2564 fixed vs what remains

### Fixed by PR #2564 ✅

| File | Change | Verified |
|------|--------|----------|
| `async_tui.py` | `_AUTH_ERROR_SIGNATURES`, `_detect_auth_error()` | Unit test PASS |
| `async_tui.py` | `_LogCapture` handler on root logger during `_execute_prompt()` | Captures 401 logs in isolation test |
| `async_tui.py` | `execution_failed` property + `_last_error` | Unit test PASS (mocked agent) |
| `chat.py:237` | `if tui.execution_failed: raise typer.Exit(1)` | Wired correctly |
| `tests/unit/test_chat_auth_exit_code.py` | 6 tests for detection + flag | All PASS |

### Still broken after PR #2564 ❌

| Issue | Detail |
|-------|--------|
| **Truthy `AutonomyResult` bypasses guard** | `if auth_error and not response:` — `AutonomyResult` is always truthy even when `output=''` |
| **Unit test gap** | Tests mock `agent.start()` → `None`; production uses `agent.astart()` → `AutonomyResult` |
| **No user-visible error on stdout** | Plain mode prints nothing; stderr-only warnings |
| **Bonus: cp1252 crash on error display** | When exception path hits `display_error()`, Rich `⚠` (U+26A0) also fails on cp1252 (related #2561) |

---

## Actual vs expected behavior

### Unexpected (actual, post-#2564)

```powershell
$env:OPENAI_API_KEY = "sk-invalid-key-for-test"
praisonai chat --output plain --model gpt-4o-mini -- "Hello"
Write-Host "Exit: $LASTEXITCODE"   # prints 0 — should be 1
```

**stderr (excerpt):**
```
openai_client.py:1465 WARNING Responses API failed, falling back to Chat Completions: Error code: 401 - ...
openai_client.py:1486 ERROR Error creating async completion: Error code: 401 - ...
chat_mixin.py:1485 WARNING [Praison] Authentication failed for openai. Check API credentials. (credential rotation not yet implemented)
```

**stdout:** *(empty)*  
**exit code:** `0` ❌

**Debug (`run_single` internals, post-#2564):**
```
RESPONSE= ''
EXEC_FAILED= False
LAST_ERROR= None
```

**Direct `astart()` inspection:**
```python
response = await agent.astart('Hello')
# AutonomyResult(success=True, output='', completion_reason='caller_mode', iterations=1, ...)
# type(response).__bool__() → True  ← guard fails
```

**Log capture during `astart()` (works):**
```python
cap.records == [
  "Responses API failed, falling back to Chat Completions: Error code: 401 - ...",
  "Error creating async completion: Error code: 401 - ...",
  "[Praison] Authentication failed for openai. Check API credentials. ..."
]
cap.find_auth_error() → "Authentication failed: check your API key/credentials."
# Auth IS detected — but guard `not response` is False because AutonomyResult is truthy
```

### Expected

| Condition | stdout | stderr | Exit code |
|-----------|--------|--------|-----------|
| Valid key, success | Model answer | minimal | **0** |
| Invalid API key | empty or one-line error | optional detail | **1** |
| Missing API key | concise message | optional | **1** |
| Rate limit 429 | error message | logged | **non-zero** |

### Competitive comparison (same test, post-#2564)

| Product | Command | User-visible error | Exit code |
|---------|---------|-------------------|-----------|
| **Hermes** | `hermes chat -q "Hello" -Q -m gpt-4o-mini` | `HTTP 401: Incorrect API key provided...` | **1** |
| **PraisonAI** | `praisonai chat --output plain -- "Hello"` | 401 in stderr logs only | **0** ❌ |

---

## Reproduction

```powershell
# Save real key, inject invalid key
$saved = $env:OPENAI_API_KEY
$env:OPENAI_API_KEY = "sk-invalid-key-for-test"

praisonai chat --output plain --model gpt-4o-mini -- "Hello"
Write-Host "Exit code: $LASTEXITCODE"   # prints 0 — should be non-zero

$env:OPENAI_API_KEY = $saved
```

### Verify unit tests pass but live fails

```powershell
cd PraisonAI\src\praisonai-code
python -m pytest tests/unit/test_chat_auth_exit_code.py -v
# 6 passed

$env:OPENAI_API_KEY = "sk-invalid-key-for-test"
praisonai chat --output plain --model gpt-4o-mini -- "Hello"
Write-Host $LASTEXITCODE
# 0 — live path uses AutonomyResult, tests mock None
```

### Python-level repro (no CLI)

```python
import os, logging, asyncio
os.environ["OPENAI_API_KEY"] = "sk-invalid-key-for-test"

from praisonai_code.cli.interactive.async_tui import AsyncTUI, AsyncTUIConfig, _LogCapture

tui = AsyncTUI(config=AsyncTUIConfig(model="gpt-4o-mini", show_logo=False))
agent = tui._get_agent()

cap = _LogCapture(level=logging.WARNING)
logging.getLogger().addHandler(cap)
response = asyncio.run(agent.astart("Hello"))
logging.getLogger().removeHandler(cap)

print("auth_found:", cap.find_auth_error())       # not None ✅
print("response:", response)                       # AutonomyResult(output='') 
print("not response:", not response)               # False ❌ — root cause
print("should_fail:", cap.find_auth_error() and not response)  # False ❌
```

---

## Architecture

### Current flow (post-#2564, still broken)

```mermaid
flowchart TB
  subgraph CLI["PraisonAI CLI"]
    CM["chat.py chat_main()"]
    TUI["async_tui.py AsyncTUI.run_single()"]
    EP["_execute_prompt()"]
    LC["_LogCapture on root logger"]
    EF["execution_failed property"]
  end
  subgraph Agents["praisonaiagents"]
    AG["agent.astart()"]
    AR["AutonomyResult success=True output=''"]
    CMIX["chat_mixin _handle_async_llm_error()"]
    EC["error_classifier AUTH ✅"]
  end
  CM --> TUI --> EP
  EP --> LC
  EP --> AG
  AG --> CMIX --> EC
  EC --> LOG["logging.warning auth failed"]
  LOG --> LC
  LC -->|"find_auth_error() ✅"| DETECT["auth detected"]
  AG --> AR
  AR --> EP
  EP -->|"if auth_error and not response"| GUARD{"not AutonomyResult?"}
  GUARD -->|"False — object is truthy"| SKIP["skip _last_error ❌"]
  SKIP --> EF
  EF -->|"False"| CM
  CM --> EXIT["exit 0 ❌"]
```

### Sequence diagram (post-#2564)

```mermaid
sequenceDiagram
  participant U as User
  participant C as chat_main
  participant T as AsyncTUI._execute_prompt
  participant L as _LogCapture
  participant A as agent.astart()
  participant O as OpenAI client

  U->>C: chat --output plain "Hello"
  C->>T: run_single(prompt)
  T->>L: addHandler(root)
  T->>A: astart(prompt)
  A->>O: chat completion
  O-->>A: HTTP 401 invalid_api_key
  A->>L: log WARNING auth failed
  A-->>T: AutonomyResult(output='') ← truthy object
  T->>L: removeHandler
  T->>T: auth_error = find_auth_error() → found ✅
  Note over T: if auth_error and not response<br/>not AutonomyResult = False ❌
  T-->>C: response='', execution_failed=False
  C-->>U: exit 0 ❌
```

### Code reference table (updated post-#2564)

| Symbol | Location | Role | Post-#2564 status |
|--------|----------|------|-------------------|
| `chat_main()` exit check | `chat.py:237–238` | `if tui.execution_failed: Exit(1)` | ✅ Wired |
| `_detect_auth_error()` | `async_tui.py:103–111` | Matches 401 signatures | ✅ Works |
| `_LogCapture.find_auth_error()` | `async_tui.py:127–132` | Scans captured records | ✅ Works live |
| **`if auth_error and not response`** | **`async_tui.py:855–858`** | Sets `_last_error` | ❌ **Broken for AutonomyResult** |
| `execution_failed` | `async_tui.py:1283–1288` | Returns `_last_error is not None` | ⚠️ Never set on auth path |
| `return str(response) if response else None` | `async_tui.py:860` | Return conversion | ⚠️ `AutonomyResult` → str may be empty |
| `classify_llm_error()` AUTH | `error_classifier.py:188–198` | Sets `should_rotate_credential=True` | ✅ |
| Auth warning log | `chat_mixin.py:1483–1485` | Logs only, no raise | ✅ Logged |
| **`AutonomyResult`** | **`agent/execution_mixin.py` astart()** | Returns on auth fail | ❌ **Truthy with empty output** |
| Unit test mock | `test_chat_auth_exit_code.py:72–76` | `start()` returns `None` | ⚠️ Does not match production |

### The broken guard (exact code)

```python
# async_tui.py:855–860 (post-#2564)
auth_error = log_capture.find_auth_error()   # ← returns message ✅
if auth_error and not response:              # ← FAILS: AutonomyResult is truthy ❌
    self._last_error = RuntimeError(auth_error)
    return f"Error: {auth_error}"

return str(response) if response else None     # ← returns '' (empty str from .output)
```

```python
# chat.py:230–238
response = tui.run_single(prompt)
if response:
    print(response)
if tui.execution_failed:                     # ← False ❌
    raise typer.Exit(1)
```

---

## Root cause (precise)

1. **PR #2564 assumed `agent.astart()` returns `None` on auth failure** (matching the mocked `start()` in unit tests).

2. **Production path returns `AutonomyResult`** with `success=True`, `output=''`, `error=None` — the autonomy layer treats auth failure as a completed run with empty output rather than an exception.

3. **`not response` is `False`** for any `AutonomyResult` instance regardless of `output` content — Python truthiness is on the object, not the output field.

4. **Auth detection works** — `_LogCapture` correctly records and `_detect_auth_error()` matches `"Authentication failed for openai"`. The failure is purely in the **response emptiness check**.

5. **Secondary issue:** When exceptions do propagate to `display_error()`, Rich emits `⚠` (U+26A0) which also crashes on cp1252 (#2561 overlap).

---

## Proposed implementation (remaining work)

### Step 1 — Normalize response before auth check (recommended)

Add a helper in `async_tui.py`:

```python
def _is_empty_agent_response(response) -> bool:
    """True when the agent produced no user-visible output."""
    if response is None:
        return True
    # AutonomyResult and similar wrappers
    output = getattr(response, "output", None)
    if output is not None:
        return not str(output).strip()
    if isinstance(response, str):
        return not response.strip()
    return False
```

Replace guard:

```python
auth_error = log_capture.find_auth_error()
if auth_error and _is_empty_agent_response(response):
    self._last_error = RuntimeError(auth_error)
    return f"Error: {auth_error}"
```

### Step 2 — Check AutonomyResult.error / success

```python
if hasattr(response, "error") and response.error:
    self._last_error = RuntimeError(str(response.error))
elif hasattr(response, "success") and response.success is False:
    self._last_error = RuntimeError("Agent execution failed")
```

Also consider setting `success=False` in `chat_mixin.py` when `should_rotate_credential=True`.

### Step 3 — Extract output for display

```python
def _extract_output(response) -> Optional[str]:
    if response is None:
        return None
    if hasattr(response, "output"):
        text = str(response.output or "").strip()
        return text or None
    return str(response).strip() or None
```

Use in `chat_main`:

```python
response = tui.run_single(prompt)
text = _extract_output(response)  # or method on TUI
if text:
    print(text)
if tui.execution_failed:
    raise typer.Exit(1)
```

### Step 4 — Fix unit tests to match production

```python
class _SilentAuthAgent:
    def start(self, prompt):
        logging.warning("Authentication failed for openai")
        return None

    async def astart(self, prompt):
        logging.warning("Authentication failed for openai")
        from praisonaiagents.autonomy import AutonomyResult  # actual import path
        return AutonomyResult(success=True, output="", ...)
```

Add integration test: subprocess with invalid key → assert exit ≠ 0.

### Step 5 — Optional user-visible error on stdout

```python
if tui.execution_failed:
    typer.echo("Authentication failed. Check API credentials.", err=True)
    raise typer.Exit(1)
```

---

## Acceptance criteria (updated)

- [ ] Invalid `OPENAI_API_KEY` → `praisonai chat --output plain -- "Hello"` exits **non-zero**
- [ ] Valid key → still exits 0 with answer
- [ ] Works when `astart()` returns `AutonomyResult(output='')` (production path)
- [ ] Works when `start()` returns `None` (legacy path — regression)
- [ ] stderr may still log details; stdout empty or concise error is OK
- [ ] Hermes-parity: script can use `$LASTEXITCODE` / `%ERRORLEVEL%` without parsing logs
- [ ] Unit test: mock `astart()` → `AutonomyResult(output='')` + auth log → exit 1
- [ ] Integration test: subprocess invalid key → exit ≠ 0
- [ ] No regression on interactive REPL mode

---

## Test plan

| # | Test | Expected |
|---|------|----------|
| 1 | Invalid key, plain one-shot (live CLI) | exit ≠ 0 |
| 2 | Valid key, plain one-shot | exit 0, answer printed |
| 3 | Unit: mock `astart()` → `AutonomyResult(output='')` + auth log | `execution_failed=True` |
| 4 | Unit: mock `start()` → `None` + auth log | `execution_failed=True` (regression) |
| 5 | Unit: successful `AutonomyResult(output='hello')` | `execution_failed=False` |
| 6 | Missing key entirely | exit ≠ 0 |
| 7 | PowerShell `$LASTEXITCODE` check | reflects failure |
| 8 | Compare Hermes invalid-key test | same script semantics |

---

## Related

- [#2561](https://github.com/MervinPraison/PraisonAI/issues/2561) — `praisonai run` Windows Unicode (display_error also emits ⚠ on cp1252)
- [#2564](https://github.com/MervinPraison/PraisonAI/pull/2564) — partial fix (log capture + guard)
- Interactive analysis: `competitive-analysis/hermes-vs-praisonai/feature-02-chat-analysis.html`

---

## Competitive reference

| Capability | Hermes `chat -q` | PraisonAI `chat --output plain` |
|------------|------------------|----------------------------------|
| Invalid key message | Clear HTTP 401 on stdout/stderr | 401 buried in logs |
| Exit code on auth fail | 1 | 0 ❌ (post-#2564) |
| Script automation | `$?` reliable | requires stderr grep |
| Valid key one-shot | works | works ✅ |

**Comment by Dhivya-Bharathy** [comment]
Reopen was blocked by permissions. Follow-up issue filed with full post-#2564 re-verification: #2568
