### ISSUE TITLE
[BUG][Terminal-Bench] test_code_agent_command_shape incompatible with Harbor pipefail wrapper

### ISSUE THREAD

**Issue by Dhivya-Bharathy** [MervinPraison/PraisonAI#3281]
# [BUG][Terminal-Bench] `test_code_agent_command_shape` assertion incompatible with Harbor command wrapper

## Labels

`bug`, `terminal-bench`, `harbor`, `examples`, `testing`

## Severity

**Medium** — latent failure; masked today by #10 (`self.env` crash) but will fail immediately after that fix

## Package / path

`examples/terminal_bench/test_integration.py` — `TestPraisonAICodeAgent.test_code_agent_command_shape`

## Related

| Item | Link |
|------|------|
| PR | [#3269](https://github.com/MervinPraison/PraisonAI/pull/3269) |
| Must fix first | #10 `PraisonAICodeAgent` `self.env` |
| Related | #11 external agent `logs_dir` |

---

## Executive summary

`test_code_agent_command_shape` is meant to verify that `PraisonAICodeAgent.run()` builds the correct headless shell command for `praisonai code`. The test mocks `environment.exec` and inspects the `command` kwarg.

**Two problems stack:**

1. **Today (#10):** test never reaches assertion — crashes on `self.env` first.
2. **After #10 fix (this issue):** test reaches assertion but uses `.startswith("praisonai code ...")`. Harbor’s `BaseInstalledAgent._exec()` **always prefixes** commands with `set -o pipefail; `. The received command begins with that prefix, so `.startswith` fails even when the adapter is **100% correct**.

This is a **test assertion bug**, not an adapter bug. The command content is right; the test checks the wrong string boundary.

---

## Background — what this test is guarding

PR #3269’s headline value is driving:

```bash
praisonai code "<instruction>" --dangerously-skip-approval --model <model>
```

inside Harbor containers. This test ensures:

| Property | Why it matters |
|----------|----------------|
| Subcommand is `praisonai code` | Not `praisonai` or `praisonai chat` |
| Instruction is shell-quoted | Prevents injection / word-splitting |
| `--dangerously-skip-approval` present | Non-TTY container won't hang on approval prompts |
| `--model` matches agent config | Benchmark reproducibility |
| Output redirected to log file | Post-run inspection via `populate_context_post_run` |

The test **should** validate these — but must account for Harbor’s exec wrapper.

---

## Environment

| Field | Value |
|-------|-------|
| Harbor | 0.20.0 |
| Python | 3.13.2 |
| Test | `examples/terminal_bench/test_integration.py` |
| Depends on | #10 fixed |

---

### Phase 1 — current (masked by #10)

```bash
export PYTHONPATH=.
pytest examples/terminal_bench/test_integration.py::TestPraisonAICodeAgent::test_code_agent_command_shape -v
```

**Observed today:**

```
AttributeError: 'PraisonAICodeAgent' object has no attribute 'env'
```

### Phase 2 — after #10 fix (this bug surfaces)

Same command after removing `env=self.env`:

```
AssertionError: assert False
 +  where False = 'set -o pipefail; praisonai code \'fix the failing test\' ...'.startswith('praisonai code \'fix the failing test\'')
```

### Simulate post-#10 without patching production

Temporarily patch only the env line locally, or apply #10 fix on a branch, then re-run pytest.

---

### Predicted full failure (after #10)

```
______________ TestPraisonAICodeAgent.test_code_agent_command_shape ______________

self = <terminal_bench.test_integration.TestPraisonAICodeAgent object at 0x...>
tmp_path = PosixPath('/tmp/pytest-of-user/pytest-N/test_code_agent_command_shape0')

    @pytest.mark.asyncio
    async def test_code_agent_command_shape(self, tmp_path):
        ...
        await agent.run(instruction, env, context)

        env.exec.assert_awaited()
        command = env.exec.await_args.kwargs.get("command", "")
>       assert command.startswith(f"praisonai code {shlex.quote(instruction)}")
E       AssertionError: assert False
E        +  where False = (
E             "set -o pipefail; praisonai code 'fix the failing test' "
E             "--dangerously-skip-approval --model openai/gpt-4o-mini > /tmp/praisonai_code.log 2>&1; ..."
E           ).startswith("praisonai code 'fix the failing test'")

examples/terminal_bench/test_integration.py:55: AssertionError
```

---

## Expected vs actual — command string comparison

Instruction used in test: `fix the failing test`  
Quoted instruction: `'fix the failing test'`

| Fragment | Test expects at position 0 | Harbor sends |
|----------|---------------------------|--------------|
| Start of string | `praisonai code` | `set -o pipefail;` |
| Instruction | `'fix the failing test'` | ✅ Present (after prefix) |
| `--dangerously-skip-approval` | Present | ✅ Present |
| `--model openai/gpt-4o-mini` | Present | ✅ Present |
| Log redirect `> /tmp/praisonai_code.log` | Not asserted | ✅ Present |
| Exit status capture | Not asserted | ✅ Present |

### Side-by-side command strings

**What the test expects (`command.startswith(...)`):**

```
praisonai code 'fix the failing test' --dangerously-skip-approval --model openai/gpt-4o-mini > ...
```

**What Harbor actually passes to `environment.exec`:**

```
set -o pipefail; praisonai code 'fix the failing test' --dangerously-skip-approval --model openai/gpt-4o-mini > ...
^^^^^^^^^^^^^^^^^
Harbor-added prefix — causes startswith failure
```

---

## Step-by-step call chain

```mermaid
sequenceDiagram
    participant T as test_code_agent_command_shape
    participant A as PraisonAICodeAgent.run
    participant E as exec_as_agent
    participant X as BaseInstalledAgent._exec
    participant M as Mock environment.exec

    T->>A: run(instruction, env, context)
    A->>A: build command string (praisonai code ...)
    A->>E: exec_as_agent(environment, command)
    E->>X: _exec(environment, command)
    X->>M: exec(command="set -o pipefail; praisonai code ...")
    M-->>T: return_code=0
    T->>T: assert command.startswith("praisonai code ...")
    Note over T: FAIL — prefix mismatch
```

| Layer | Responsibility |
|-------|----------------|
| `PraisonAICodeAgent.run()` | Build adapter-specific bash script |
| `exec_as_agent()` | Run as default agent user |
| `_exec()` | Add `set -o pipefail;`, logging, error classification |
| `environment.exec()` | Actually run in container (mocked in test) |
| Test assertion | **Incorrectly assumes no Harbor wrapper** |

---

### Full test code (current)

```python
@pytest.mark.asyncio
async def test_code_agent_command_shape(self, tmp_path):
    from examples.terminal_bench.praisonai_code_agent import PraisonAICodeAgent

    agent = PraisonAICodeAgent(
        model_name="openai/gpt-4o-mini", logs_dir=str(tmp_path)
    )
    env = Mock()
    env.exec = AsyncMock(
        return_value=SimpleNamespace(stdout="", stderr="", return_code=0)
    )
    context = SimpleNamespace(metadata=None)

    instruction = "fix the failing test"
    await agent.run(instruction, env, context)

    env.exec.assert_awaited()
    command = env.exec.await_args.kwargs.get("command", "")
    assert command.startswith(f"praisonai code {shlex.quote(instruction)}")  # TOO STRICT
    assert "--dangerously-skip-approval" in command
    assert "--model openai/gpt-4o-mini" in command
```

### Harbor wrapper (framework — intentional)

```python
# harbor/agents/installed/base.py — BaseInstalledAgent._exec
result = await environment.exec(
    command=f"set -o pipefail; {command}",
    user=user,
    env=env,
    cwd=cwd,
    timeout_sec=timeout_sec,
)
```

**Why Harbor adds `set -o pipefail`:**

| Without pipefail | With pipefail |
|------------------|---------------|
| `cmd1 \| cmd2` exit code = exit code of last command | Pipeline fails if **any** stage fails |
| Silent failures in benchmarks | Correct error propagation to Harbor |
| False “success” trajectories | Aligns with bash best practices in containers |

This wrapper applies to **all** installed agents (codex, claude-code, praisonai-code, etc.) — not specific to PraisonAI.

### What the test gets right

| Assertion | Still valid after fix? |
|-----------|------------------------|
| `env.exec.assert_awaited()` | ✅ Yes |
| `"--dangerously-skip-approval" in command` | ✅ Yes |
| `"--model openai/gpt-4o-mini" in command` | ✅ Yes |
| `.startswith("praisonai code ...")` | ❌ No — use `in command` |

### Adapter command builder (unchanged — correct)

From `praisonai_code_agent.py`:

```python
command = (
    f"praisonai code {shlex.quote(instruction)} "
    f"--dangerously-skip-approval "
    f"--model {shlex.quote(model)} "
    "> /tmp/praisonai_code.log 2>&1; "
    "status=$?; "
    "cp /tmp/praisonai_code.log /tmp/praisonai_code_run.log 2>/dev/null || true; "
    "exit $status"
)
```

The adapter builds a **multi-statement bash script** with logging and exit propagation. Harbor then wraps the **entire script** in `set -o pipefail; ...`.

---

## Failure timeline across fixes

| Stage | #10 status | #12 status | Test result |
|-------|------------|------------|-------------|
| Current main + PR | Broken (`self.env`) | Latent | FAIL — AttributeError |
| After #10 only | Fixed | Unfixed | FAIL — AssertionError startswith |
| After #10 + #12 | Fixed | Fixed | **PASS** |
| After #10 + #12 + #11 | All fixed | Fixed | Full file 6/6 PASS |

---

## User impact

| Audience | Impact |
|----------|--------|
| PR author | Fixes #10, sees new red test — may incorrectly “fix” adapter command |
| Reviewers | Confusion: adapter command looks correct in code but test fails |
| Benchmark ops | **None at runtime** — Harbor always used pipefail wrapper; production was fine |
| Future maintainers | May weaken test or remove pipefail assertion incorrectly |

**Risk if “fixed” wrong:** someone might strip Harbor wrapper or change adapter to avoid prefix — **don't** — fix the test only.

---

### Option 1 — Substring match (recommended)

Validates adapter content regardless of Harbor prefix:

```diff
         env.exec.assert_awaited()
         command = env.exec.await_args.kwargs.get("command", "")
-        assert command.startswith(f"praisonai code {shlex.quote(instruction)}")
+        assert f"praisonai code {shlex.quote(instruction)}" in command
         assert "--dangerously-skip-approval" in command
         assert "--model openai/gpt-4o-mini" in command
```

### Option 2 — Explicit dual assertion (documents Harbor behavior)

```python
assert command.startswith("set -o pipefail; ")
assert f"praisonai code {shlex.quote(instruction)}" in command
assert "--dangerously-skip-approval" in command
assert "--model openai/gpt-4o-mini" in command
```

**Best for:** teaching future contributors why prefix exists.

### Option 3 — Strip prefix helper

```python
def _inner_command(raw: str) -> str:
    prefix = "set -o pipefail; "
    return raw[len(prefix):] if raw.startswith(prefix) else raw

inner = _inner_command(command)
assert inner.startswith(f"praisonai code {shlex.quote(instruction)}")
```

**Best for:** strict startswith on adapter portion only.

### Option 4 — Mock `exec_as_agent` directly

Patch at adapter boundary to capture command before Harbor `_exec` wrapping. Heavier; usually unnecessary unless testing adapter in complete isolation from Harbor base class.

### Do not

| Anti-pattern | Why |
|--------------|-----|
| Remove `set -o pipefail` from Harbor | Upstream framework behavior |
| Change adapter to avoid pipelines | Doesn't remove wrapper anyway |
| Delete this test | Only automated guard for CLI command shape |

---

## Extended verification matrix

| # | Check | Command | Expected |
|---|-------|---------|----------|
| 1 | #10 fixed | manual / branch | No AttributeError on run |
| 2 | This test | `pytest ...::test_code_agent_command_shape` | PASS |
| 3 | Model flag | inspect command in assert | contains `--model openai/gpt-4o-mini` |
| 4 | Approval skip | inspect command | contains `--dangerously-skip-approval` |
| 5 | Quoting | instruction with spaces | properly shlex-quoted in command |
| 6 | Full file | `pytest test_integration.py` | 6/6 with #10 + #11 |

### Bonus test case (optional hardening)

Add parametrized instruction with shell metacharacters:

```python
@pytest.mark.parametrize("instruction", [
    "fix the failing test",
    "echo hello; rm -rf /",  # must be quoted safely
    "task with 'single quotes'",
])
async def test_code_agent_quotes_instruction(self, tmp_path, instruction):
    ...
    assert shlex.quote(instruction) in command
```

---

## Acceptance criteria

- [ ] Test passes on Harbor 0.20 after #10 is fixed
- [ ] Assertion validates full adapter command **content** (subcommand, flags, model)
- [ ] Test does not require command to start at character 0 with `praisonai code`
- [ ] No changes required to `praisonai_code_agent.py` for this issue alone
- [ ] Comment in test (optional) noting Harbor `set -o pipefail;` wrapper

---

## References

| Resource | URL |
|----------|-----|
| PR #3269 | https://github.com/MervinPraison/PraisonAI/pull/3269 |
| Harbor `_exec` | `harbor/agents/installed/base.py` |
| Related #10 | `self.env` AttributeError — blocks test earlier |
| Related #11 | External agent `logs_dir` |
